import type { Customer, Property } from '@/lib/types';

// ---- کارخانه‌های داده (مطابق ستون‌های واقعی جدول customers/properties) ----

const baseCustomer: Customer = {
  id: 'c1',
  name: 'مشتری تستی',
  first_name: 'مشتری',
  last_name: 'تستی',
  mobile: '09120000000',
  secondary_phone: '',
  address: '',
  customer_type: 'personal',
  transaction_intention: 'buy',
  transaction_role: 'buyer',
  budget_min: 0,
  budget_max: 0,
  preferred_category: 'residential',
  preferred_property_types: ['apartment'],
  preferred_province_ids: [],
  preferred_county_ids: [],
  preferred_city_ids: [],
  min_area: 0,
  max_area: 0,
  bedrooms: 0,
  required_features: [],
  preferred_floor: 0,
  parking_required: false,
  elevator_required: false,
  property_preferences: {},
  urgency: 'normal',
  temperature: 'warm',
  lead_source: 'test',
  assigned_consultant_id: '',
  notes: '',
  tags: [],
  last_contact: '',
  next_followup: '',
  status: 'active',
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-01-01T00:00:00Z',
};

// property_preferences در واقعیت JSON است (در TS نوع توپ‌سطحی string|number|... دارد)؛
// فرم واقعی به‌صورت توپ‌در-توپ ذخیره می‌کند → در تست با کست عبور می‌کنیم
export function makeCustomer(
  overrides: Partial<Omit<Customer, 'property_preferences'>> & { property_preferences?: Record<string, unknown> } = {},
): Customer {
  return { ...baseCustomer, ...overrides } as Customer;
}

const baseProperty: Property = {
  id: 'p1',
  title: 'فایل تستی',
  description: '',
  transaction_type: 'sell',
  transaction_role: 'seller',
  category: 'residential',
  property_type: 'apartment',
  status: 'active',
  is_hot: false,
  is_featured: false,
  is_active: true,
  owner_id: 'o1',
  assigned_consultant_id: '',
  province_id: 'prov-1',
  county_id: 'county-1',
  district_id: 'dist-1',
  city_id: 'city-1',
  neighborhood_id: 'hood-1',
  street: '',
  address: '',
  postal_code: '',
  latitude: 0,
  longitude: 0,
  land_area: 0,
  building_area: 0,
  rooms: 0,
  bedrooms: 0,
  floor: 0,
  total_floors: 0,
  unit_number: '',
  building_age: 0,
  parking: false,
  storage: false,
  elevator: false,
  balcony: false,
  yard: false,
  garden: false,
  pool: false,
  security: false,
  heating: '',
  cooling: '',
  sale_price: 0,
  deposit_price: 0,
  monthly_rent: 0,
  price_per_meter: 0,
  owner_requested_price: 0,
  participation_price: 0,
  negotiable: false,
  payment_conditions: '',
  commission: 0,
  owner_notes: '',
  owner_relationship: '',
  owner_followup_status: '',
  images: [],
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-01-01T00:00:00Z',
};

export function makeProperty(overrides: Partial<Property> = {}): Property {
  return { ...baseProperty, ...overrides };
}

